require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2

Style/HashSyntax:
  Enabled: false

Metrix/MethodLength:
  Exclude:
   - 'app/service/openai/*'
   - 'app/models/vocabulary.rb'
   - 'app/controllers/auth/*'